version: '3.5'

services:
  postgres:
    image: postgres
    #restart: always
    container_name: postgres
    ports:
      - 6500:5432
    environment:
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=golang-gorm
      - POSTGRES_PORT=6500
    #env_file:
    #  - ./app.env
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:


# version: '3.8'
# services:
#   db:
#     image: postgres:14.1-alpine
#     restart: always
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#     ports:
#       - '5432:5432'
#     volumes: 
#       - db:/var/lib/postgresql/data
# volumes:
#   db:
#     driver: local